/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DateKey = IDL.Text;
export const EventInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
});
export const EventId = IDL.Nat;
export const Event = IDL.Record({
  'id' : EventId,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Opt(IDL.Text),
});
export const DayEvents = IDL.Record({
  'dateKey' : DateKey,
  'events' : IDL.Vec(Event),
});

export const idlService = IDL.Service({
  'addEvent' : IDL.Func([DateKey, EventInput], [EventId], []),
  'deleteEvent' : IDL.Func([EventId], [], []),
  'getEvents' : IDL.Func([DateKey], [IDL.Vec(Event)], ['query']),
  'getEventsByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DayEvents)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DateKey = IDL.Text;
  const EventInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
  });
  const EventId = IDL.Nat;
  const Event = IDL.Record({
    'id' : EventId,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Opt(IDL.Text),
  });
  const DayEvents = IDL.Record({
    'dateKey' : DateKey,
    'events' : IDL.Vec(Event),
  });
  
  return IDL.Service({
    'addEvent' : IDL.Func([DateKey, EventInput], [EventId], []),
    'deleteEvent' : IDL.Func([EventId], [], []),
    'getEvents' : IDL.Func([DateKey], [IDL.Vec(Event)], ['query']),
    'getEventsByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DayEvents)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };