/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DateKey = string;
export interface DayEvents { 'dateKey' : DateKey, 'events' : Array<Event> }
export interface Event {
  'id' : EventId,
  'title' : string,
  'createdAt' : bigint,
  'color' : [] | [string],
  'description' : [] | [string],
}
export type EventId = bigint;
export interface EventInput {
  'title' : string,
  'color' : [] | [string],
  'description' : [] | [string],
}
export interface _SERVICE {
  'addEvent' : ActorMethod<[DateKey, EventInput], EventId>,
  'deleteEvent' : ActorMethod<[EventId], undefined>,
  'getEvents' : ActorMethod<[DateKey], Array<Event>>,
  'getEventsByMonth' : ActorMethod<[bigint, bigint], Array<DayEvents>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];